ADDRESS: "localhost:8015"
DB_USER: "rqx78693"
DB_PASS: "1CY68qga6Ses37LI"
DB_HOST: "98538591-7217-4024-b027-8baa776ffad1.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud"
DB_PORT: "30875"
DB_NAME: "bludb"
ENABLE_DB: true
